config/routes.rb
ClassifiedSite::Application.routes.draw do
	match "/users/current" => "users#owner"
	match "/sites/sitemap" => "sites#sitemap"
  resources :sites
  resources :feed_entries
  resources :subscribers
  resources :classifieds
	match "/users/nav" => "users#nav"
  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  root :to => "sites#show"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
  match "/packages" => "home#index"
end

app/models/feed_entry.rb
class FeedEntry < ActiveRecord::Base
  attr_accessible :guid, :name, :published_at, :summary, :url, :site_id
  belongs_to :site
  def to_param
  	"#{id}-#{name}".parameterize
  end
  
  def self.random
  	if (c = count) != 0
  		all limit: 10, order: "published_at desc", offset: rand(c)
  	end
  end

	def self.update_from_feed(feed_url, site_id)
		feed = Feedzirra::Feed.fetch_and_parse(feed_url)
		feed.entries.each do |entry|
		  unless exists? :guid => entry.id
		    create!(
		      :name         => entry.title,
		      :summary      => entry.summary,
		      :url          => entry.url,
		      :published_at => entry.published,
		      :guid         => entry.entry_id,
		      :site_id      => site_id
		    )
		  end
		end
	end
	
	def self.rent_tallahassee
		site_id = 1
		feed = Feedzirra::Feed.fetch_and_parse("https://dl.dropbox.com/s/ccvuhf27l1c7pos/tallahassee-sub.xml?token_hash=AAF18tRJe7lyr6sQi86rsxiiIntajcYcXM_oT7V46Uj4NA&dl=1")
		feed.entries.each do |entry|
		  unless exists? :guid => entry.id
		    create!(
		      :name         => entry.title,
		      :summary      => entry.summary,
		      :url          => entry.url,
		      :published_at => entry.published,
		      :guid         => entry.entry_id,
		      :site_id      => site_id
		    )
		  end
		end
	end
	
	def self.rent_philadelphia
		site_id = 3
		feed = Feedzirra::Feed.fetch_and_parse("https://dl.dropbox.com/s/3ywcpfp593kevvo/philadelphia-sub.xml?token_hash=AAGFpLIldBwxwKcp-7GdlJbzeY6GvSf3QB3LR6xxQ_b3OQ&dl=1")
		feed.entries.each do |entry|
		  unless exists? :guid => entry.id
		    create!(
		      :name         => entry.title,
		      :summary      => entry.summary,
		      :url          => entry.url,
		      :published_at => entry.published,
		      :guid         => entry.entry_id,
		      :site_id      => site_id
		    )
		  end
		end
	end
	
	def self.rent_san_francisco
		site_id = 4
		feed = Feedzirra::Feed.fetch_and_parse("https://dl.dropbox.com/s/bclct02mbl762lg/sanfrancisco-sub.xml?token_hash=AAFhS85MPmSWgA64Gsf7gL7dj6ZrXnhWuYjW4_-elXrAhQ&dl=1")
		feed.entries.each do |entry|
		  unless exists? :guid => entry.id
		    create!(
		      :name         => entry.title,
		      :summary      => entry.summary,
		      :url          => entry.url,
		      :published_at => entry.published,
		      :guid         => entry.entry_id,
		      :site_id      => site_id
		    )
		  end
		end
	end
	
	def self.rentals_in_fl(city)
		feed_url = "https://dl.dropbox.com/s/s4nokapjlotpy0h/rif-daytona.xml?token_hash=AAGZxsrVcAiDColNDvA_YRD-_x5GrA8yMMtxHn3Y6cQIzQ&dl=1" if city == "daytona"
		feed_url = "https://dl.dropbox.com/s/nj5ws8t4z544zw8/rif-fortlauderdale.xml?token_hash=AAFBtawspaAETLBFNNEuAi0aTzE14baG73jkDd1u1YVjhw&dl=1" if city == "fortlauderdale"
		feed_url = "https://dl.dropbox.com/s/iqam7mvuc42kj0w/rif-fortmyers.xml?token_hash=AAF914l8czFNvhNEyul2rLT6MhC2uiAM9YTQLr9FQt3QXA&dl=1" if city == "fortmyers"
		feed_url = "https://dl.dropbox.com/s/md2zn24veecjlym/rif-gainesville.xml?token_hash=AAGcQ0rTuUjb0sGezbB0KOWnFHRa_1QFj8n0E4Y1mekAmQ&dl=1" if city == "gainesville"
		feed_url = "https://dl.dropbox.com/s/ipmb1ra4j0rjj4u/rif-jacksonville.xml?token_hash=AAH6MYKejkGGPeonHFSQ6gRxn-Y4co-ZJgC_r85xg3YJWA&dl=1" if city == "jacksonville"
		feed_url = "https://dl.dropbox.com/s/2xxge0cp8koun5o/rif-keys.xml?token_hash=AAF4_G4b1SPVPYGlyNvWcpdx9KsFZ_UC1KEiUZlxrEXJRA&dl=1" if city == "keys"
		feed_url = "https://dl.dropbox.com/s/wx840s572huwipb/rif-miami.xml?token_hash=AAFeqCI1BxIidL4F3Rqo2jxGRnhrLtsckinrcv1-2lM1GQ&dl=1" if city == "miami"
		feed_url = "https://dl.dropbox.com/s/86tra9ufqr06ndd/rif-orlando.xml?token_hash=AAEI-jZe6ZkQwi2lORbmLoLuoabjROkJlvBCDVTAEzvtWg&dl=1" if city == "orlando"
		feed_url = "https://dl.dropbox.com/s/8c1skm4o0b11a2i/rif-panamacity.xml?token_hash=AAFsjLB7sQhoiqdXXO9chZKySLWGR3wERG6iiSafRZpr7Q&dl=1" if city == "panamacity"
		feed_url = "https://dl.dropbox.com/s/stmhs1oh21e7l96/rif-sarasota.xml?token_hash=AAH07xi9yDhObvdRhnSg6vnGccHWkTpxb9Sx5P0n8ggVvg&dl=1" if city == "sarasota"
		feed_url = "https://dl.dropbox.com/s/74o14vejlci26tz/rif-staugustine.xml?token_hash=AAGOjKoCdnWLxsZtpoO1DiJAAO1Kyxw_iXJxz8wrT_ohKw&dl=1" if city == "staugustine"
		feed_url = "https://dl.dropbox.com/s/hw2pwz1cqiarl1h/rif-tallahassee.xml?token_hash=AAGduqNKtjJWw3gWy5qmLpqZ-Eg_AgvIspNZs0hX182BUQ&dl=1" if city == "tallahassee"
		feed_url = "https://dl.dropbox.com/s/o4miybno9tj4uau/rif-tampa.xml?token_hash=AAF7oeBE7tXsW6Z1iVFGXLz_gp9KbIN23MhmqFX_cJe8-w&dl=1" if city == "tampa"
		feed_url = "https://dl.dropbox.com/s/ml41brq8mwwjwl3/rif-westpalmbeach.xml?token_hash=AAG3fuc0K3785RBUjxruSxo_FBkLb_UXgyebAqKV8ODxMg&dl=1" if city == "westpalmbeach"
		site_id = 5
		feed = Feedzirra::Feed.fetch_and_parse(feed_url)
		feed.entries.each do |entry|
		  unless exists? :guid => entry.id
		    create!(
		      :name         => entry.title,
		      :summary      => entry.summary,
		      :url          => entry.url,
		      :published_at => entry.published,
		      :guid         => entry.entry_id,
		      :site_id      => site_id
		    )
		  end
		end
	end	

end

app/controllers/feed_entries_controller.rb
class FeedEntriesController < ApplicationController
  caches_page :show
  cache_sweeper :feed_entry_sweeper
	load_and_authorize_resource
  # GET /feed_entries
  # GET /feed_entries.json
  def index
    @feed_entries = FeedEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feed_entries }
    end
  end

  # GET /feed_entries/1
  # GET /feed_entries/1.json
  def show
		@site = Site.find_by_domain(request.domain)
  	@page_caching = true
    @feed_entry = FeedEntry.find(params[:id].to_i)
    @feed_entries = FeedEntry.random
    @meta_title = "#{@meta_title} - #{@feed_entry.name}"

    respond_to do |format|
      format.html # show.html.erb
      format.json { rendfer json: @feed_entry }
    end
  end

  # GET /feed_entries/new
  # GET /feed_entries/new.json
  def new
    @feed_entry = FeedEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed_entry }
    end
  end

  # GET /feed_entries/1/edit
  def edit
    @feed_entry = FeedEntry.find(params[:id])
  end

  # POST /feed_entries
  # POST /feed_entries.json
  def create
    @feed_entry = FeedEntry.new(params[:feed_entry])

    respond_to do |format|
      if @feed_entry.save
        format.html { redirect_to @feed_entry, notice: 'Feed entry was successfully created.' }
        format.json { render json: @feed_entry, status: :created, location: @feed_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @feed_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feed_entries/1
  # PUT /feed_entries/1.json
  def update
    @feed_entry = FeedEntry.find(params[:id])

    respond_to do |format|
      if @feed_entry.update_attributes(params[:feed_entry])
        format.html { redirect_to @feed_entry, notice: 'Feed entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feed_entries/1
  # DELETE /feed_entries/1.json
  def destroy
    @feed_entry = FeedEntry.find(params[:id])
    @feed_entry.destroy

    respond_to do |format|
      format.html { redirect_to feed_entries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/feed_entries_helper.rb
module FeedEntriesHelper
end

app/views/feed_entries/_form.html.erb
<%= simple_form_for(@feed_entry) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :summary %>
    <%= f.input :url %>
    <%= f.input :published_at %>
    <%= f.input :guid %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/feed_entries/edit.html.erb
<h1>Editing feed_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed_entry %> |
<%= link_to 'Back', feed_entries_path %>

app/views/feed_entries/index.html.erb
<h1>Listing feed_entries</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Summary</th>
    <th>Url</th>
    <th>Published at</th>
    <th>Guid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feed_entries.each do |feed_entry| %>
  <tr>
    <td><%= feed_entry.name %></td>
    <td><%= feed_entry.summary %></td>
    <td><%= feed_entry.url %></td>
    <td><%= feed_entry.published_at %></td>
    <td><%= feed_entry.guid %></td>
   	<td><%= feed_entry.site_id %></td>
    <td><%= link_to 'Show', feed_entry %><%= link_to 'Edit', edit_feed_entry_path(feed_entry) %></td>
    <td><%= link_to 'Destroy', feed_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/feed_entries/new.html.erb
<h1>New feed_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', feed_entries_path %>

app/views/feed_entries/show.html.erb
<div class="span6 offset1">
	<div class="social pull-right">
		<div class="fb-send" data-colorscheme="light" data-href="http://www.rent-tallahassee.com/feed_entries/<%= @feed_entry.id %>"></div> 
		<a href="https://twitter.com/intent/tweet?button_hashtag=RentTallahassee&text=<%= @feed_entry.name %> http://rent-tallahassee.com/feed_entries/<%= @feed_entry.id %>" class="twitter-hashtag-button" data-lang="en" data-related="jasoncosta" style="margin-bottom: -4px;">Tweet #RentTallahassee</a>
	</div>
	<p>
		<h1>
			<%= @feed_entry.name %>
		</h1>
	</p>

	<p>
		<%= raw @feed_entry.summary %>
	</p>

	<p>
		<a href="<%= @feed_entry.url %>" class="btn btn-danger">See More</a>
	</p>

	<p>
		<b>Published at:</b>
		<%= @feed_entry.published_at %>
	</p>
	<table class="table table-hover">
		<tr>
			<th><h2><%= link_to "More Listings", site_path(@feed_entry.site_id) %></h2></th>
		</tr>
		<% @feed_entries.each do |feed| %>
		<tr>
			<td>
				<% if feed.site_id == @site.id %>
					<ul class="unstyled lead">
						<li>
							
								<%= link_to truncate(feed.name, length: 50), feed_entry_path("#{feed.id}-#{feed.name.parameterize}") %>
							
						</li>
					</ul>
				<% end %>
			</td>
		</tr>
		<% end %>
	</table>
</div>
<div class="span4">
	<%= link_to 'Back', site_path(@feed_entry.site_id), class: 'btn btn-small btn-primary btn-block' %>
	<div class="listing-comments">
		<div class="fb-comments" data-href="http://www.Rent-Tallahassee.com/feed_entries/<%= "#{@feed_entry.id}-#{@feed_entry.name}".parameterize %>" data-width="350" data-num-posts="2"></div>
	</div>
</div>