config/routes.rb
ClassifiedSite::Application.routes.draw do
	match "/users/current" => "users#owner"
	match "/sites/sitemap" => "sites#sitemap"
  resources :sites
  resources :feed_entries
  resources :subscribers
  resources :classifieds
	match "/users/nav" => "users#nav"
  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  root :to => "sites#show"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
  match "/packages" => "home#index"
end

app/models/classified.rb
class Classified < ActiveRecord::Base
  attr_accessible :content, :headline, :email, :user_id

  
  def to_param
  	"#{id}-#{headline}".parameterize
  end
end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
	load_and_authorize_resource
  # GET /classifieds/1
  # GET /classifieds/1.json
  def show
    @classified = Classified.find(params[:id])
		@meta_title = "#{@meta_title} - #{@classified.headline}"
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @classified }
    end
  end

  # GET /classifieds/new
  # GET /classifieds/new.json
  def new
    @classified = Classified.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @classified }
    end
  end

  # GET /classifieds/1/edit
  def edit
    @classified = Classified.find(params[:id])
  end

  # POST /classifieds
  # POST /classifieds.json
  def create
    @classified = Classified.new(params[:classified])

    respond_to do |format|
      if @classified.save
        format.html { redirect_to @classified, notice: 'Classified was successfully created.' }
        format.json { render json: @classified, status: :created, location: @classified }
      else
        format.html { render action: "new" }
        format.json { render json: @classified.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /classifieds/1
  # PUT /classifieds/1.json
  def update
    @classified = Classified.find(params[:id])

    respond_to do |format|
      if @classified.update_attributes(params[:classified])
        format.html { redirect_to @classified, notice: 'Classified was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @classified.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classifieds/1
  # DELETE /classifieds/1.json
  def destroy
    @classified = Classified.find(params[:id])
    @classified.destroy

    respond_to do |format|
      format.html { redirect_to classifieds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

app/views/classifieds/_form.html.erb
<%= simple_form_for(@classified) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :headline %>
    <%= f.input :content %>
    
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <%= f.input :email %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/classifieds/edit.html.erb
<h1>Editing classified</h1>

<%= render 'form' %>

<%= link_to 'Show', @classified %> |
<%= link_to 'Back', classifieds_path %>

app/views/classifieds/new.html.erb
<div class="span5 offset2">
	<h1>Create Listing</h1>
	<% if user_signed_in? %> 
		<%= render 'form' %>
	<% end %>
	<%= link_to 'Back', classifieds_path %>
</div>
<div class="span3">
	<div class="well well-small">
		<h3>Get the most out of your listing by following these guidelines:</h3>
		<ol>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ol>
	</div>
</div>

app/views/classifieds/show.html.erb
<div class="span2">
	<table class="table">
		<tr>
			<td><a href="#image1" role="button" class="btn" data-toggle="modal"><img src="http://lorempixel.com/120/120/city/1"></a></td>
			<div id="image1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h3 id="myModalLabel">image1</h3>
				</div>
				<div class="modal-body">
					<img src="http://lorempixel.com/120/120/city/1">
				</div>
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
				</div>
			</div>
		</tr>
		<tr>
			<td><a href="#image1" role="button" class="btn" data-toggle="modal"><img src="http://lorempixel.com/120/120/city/1"></a></td>
			<div id="image1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h3 id="myModalLabel">image1</h3>
				</div>
				<div class="modal-body">
					<img src="http://lorempixel.com/120/120/city/2">
				</div>
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
				</div>
			</div>
		</tr>
		<tr>
			<td><a href="#image1" role="button" class="btn" data-toggle="modal"><img src="http://lorempixel.com/120/120/city/1"></a></td>
			<div id="image1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h3 id="myModalLabel">image1</h3>
				</div>
				<div class="modal-body">
					<img src="http://lorempixel.com/120/120/city/3">
				</div>
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
				</div>
			</div>
		</tr>
	</table>
</div>
<div class="span6">
	<h3>
		<%= @classified.headline %>
	</h3>
	<p>
		<%= simple_format(raw @classified.content) %>
	</p>
</div>
<div class="span4">
	<% if user_signed_in? %>
		<% if current_user.has_role? :admin %>
			<%= link_to 'Edit this Rental', edit_classified_path(@classified), class: 'btn btn-block' %>
		<% end %>
	<% end %>
	<%= link_to 'Reserve This Rental', '', class: 'btn btn-success btn-block btn-large' %>

	<%= link_to 'Back', classifieds_path, class: 'btn btn-block' %>
	<div class="listing-comments">
		<div class="fb-comments" data-href="http://www.Rent-Tallahassee.com/classifieds/<%= "#{@classified.id}-#{@classified.headline}".parameterize %>" data-width="350" data-num-posts="2"></div>
	</div>
</div>