config/routes.rb
ClassifiedSite::Application.routes.draw do
	match "/users/current" => "users#owner"
	match "/sites/sitemap" => "sites#sitemap"
  resources :sites
  resources :feed_entries
  resources :subscribers
  resources :classifieds
	match "/users/nav" => "users#nav"
  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  root :to => "sites#show"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
  match "/packages" => "home#index"
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  attr_accessible :email, :site_id
  validates_format_of :email, with: /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_uniqueness_of :email
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
	load_and_authorize_resource
  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscribers }
    end
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/new
  # GET /subscribers/new.json
  def new
    @subscriber = Subscriber.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/1/edit
  def edit
    @subscriber = Subscriber.find(params[:id])
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(params[:subscriber])

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to root_path, notice: 'Subscriber was successfully created.' }
        format.json { render json: @subscriber, status: :created, location: @subscriber }
      else
        format.html { render action: "new" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subscribers/1
  # PUT /subscribers/1.json
  def update
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      if @subscriber.update_attributes(params[:subscriber])
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber = Subscriber.find(params[:id])
    @subscriber.destroy

    respond_to do |format|
      format.html { redirect_to subscribers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= simple_form_for(@subscriber) do |f| %>
  <%= f.error_notification %>

    <%= f.input :email %>
    <%= f.hidden_field :site_id, value: @site.id %>
    <%= f.button :submit, 'Continue', class: 'btn btn-primary' %>
    <div id="gplus">
    <div class="g-plusone" data-annotation="bubble" data-href="http://www.Rent-Tallahassee.com"></div>
		</div>
<% end %>

app/views/subscribers/edit.html.erb
<h1>Editing subscriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

app/views/subscribers/index.html.erb
<h1>Listing subscribers</h1>

<table>
  <tr>
    <th>Email</th>
    <th>site_id</th>
    <th></th>
    <th></th>
  </tr>

<% @subscribers.each do |subscriber| %>
  <tr>
    <td><%= subscriber.email %></td>
    <td><%= subscriber.site_id %></td>
    <td><%= link_to 'Show', subscriber %></td>
    <td>
		  <%= link_to 'Edit', edit_subscriber_path(subscriber) %>
		  <%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscriber', new_subscriber_path %>

app/views/subscribers/new.html.erb
<h1>New subscriber</h1>

<%= render 'form' %>

<%= link_to 'Back', subscribers_path %>

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @subscriber.email %>
</p>


<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>