config/routes.rb
ClassifiedSite::Application.routes.draw do
	match "/users/current" => "users#owner"
	match "/sites/sitemap" => "sites#sitemap"
  resources :sites
  resources :feed_entries
  resources :subscribers
  resources :classifieds
	match "/users/nav" => "users#nav"
  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  root :to => "sites#show"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
  match "/packages" => "home#index"
end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :name, :hero_unit, :call_to_subscribe, :side_box_1_title, :side_box_1_text, :side_box_2_title, :side_box_2_text, :domain, :meta_title, :meta_keywords, :meta_description
  has_many :subscribers
  accepts_nested_attributes_for :subscribers
  has_many :feed_entries
  has_many :classifieds
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
	load_and_authorize_resource
  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites }
    end
  end

	def sitemap
		@feed_entries = FeedEntry.all
		respond_to do |format|
			format.xml
		end
	end

  # GET /sites/1
  # GET /sites/1.json
  def show
  	unless params[:id] != nil
			@site = Site.find_by_domain(request.domain)
		else
			@site = Site.find(params[:id])
		end
		@classifieds = Classified.all
	  @subscriber = Subscriber.new
	  @meta_title = @site.meta_title
	  @meta_keywords = @site.meta_keywords
	  @meta_description = @site.meta_description
	  @site_results = FeedEntry.where(site_id: @site.id).order("created_at DESC")
	  @web_results = @site_results.page(params[:page]).per_page(10)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
    @classifieds = Classified.all
    @subscriber = Subscriber.new
    @meta_title = "#{@meta_title} - Apartments, Condos, and Houses"
    @web_results = FeedEntry.all(:limit => 10, :order => "published_at desc")
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { respond_with_bip(@site) }
      else
        format.html { render action: "edit" }
        format.json { respond_with_bip(@site) }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_display-table.html.erb
<div id="web_results">
	<table class="table table-hover">
		<% @classifieds.each do |classified| %>
			<% if classified.site_id == @site.id %>
				<tr>
					<td>
						<div class="well">
							<span class="badge badge-warning">Verified</span>
							<div class="social pull-right">
								<div class="fb-send" data-colorscheme="light" data-href="http://www.rent-tallahassee.com/classifieds/<%= classified.id %>"></div> 
								<a href="https://twitter.com/intent/tweet?button_hashtag=RentTallahassee&text=<%= classified.headline %> http://rent-tallahassee.com/classifieds/<%= classified.id %>" class="twitter-hashtag-button" data-lang="en" data-related="jasoncosta" style="margin-bottom: -4px;">Tweet #RentTallahassee</a>
							</div>
							<ul class="unstyled">
								<li><h4><%= link_to truncate(classified.headline, length: 140), classified_path(classified) %></h4></li>
								<li><%= truncate classified.content, length: 100 %></li>
								<li>
									<img src="http://lorempixel.com/40/40/city/1">
									<img src="http://lorempixel.com/40/40/city/2">
									<img src="http://lorempixel.com/40/40/city/3">
									<img src="http://lorempixel.com/40/40/city/4">
								</li>
							</ul>
							<%= link_to 'Show', classified, class: 'btn btn-info btn-block' %>
							<button type="button" class="btn btn-success btn-block" data-toggle="collapse" data-target="#fbc-<%= classified.id %>">
								Leave a Comment
							</button>
							<% if user_signed_in? %>
								<% if current_user.has_role? :admin %>
									<div class="pull-right">
										<%= link_to 'Edit', edit_classified_path(classified), class: 'btn btn-mini btn-danger' %>
										<%= link_to 'Destroy', classified, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
									</div>
								<% end %>
							<% end %>
							<div id="fbc-<%= classified.id %>" class="listing-comments collapse">
								<div class="fb-comments" data-href="http://www.Rent-Tallahassee.com/classifieds/<%= "#{classified.id}-#{classified.headline}".parameterize %>" data-width="420" data-num-posts="2"></div>
							</div>
						</div>
					</td>
				</tr>
			<% end %>
		<% end %>
	
		<% @web_results.each do |web| %>
			<tr>
				<td>
					<% if web.site_id == @site.id %>
						<div class="alert">
							<a href="https://twitter.com/intent/tweet?button_hashtag=RentTallahassee&text=<%= web.name %> <%= web.url %>" class="twitter-hashtag-button pull-right" data-lang="en" data-related="jasoncosta">Tweet #RentTallahassee</a>
							<ul class="unstyled">
								<li><h4><%= link_to truncate(web.name, length: 140), feed_entry_path(web) %></h4></li>
								<li><%= raw web.summary %></li>
								<li>
								</li>
							</ul>
						</div>
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>
</div>
<%= will_paginate @web_results %>

app/views/sites/_form.html.erb
<%= simple_form_for(@site) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :hero_unit %>
    <%= f.input :call_to_subscribe %>
    <%= f.input :side_box_1_title %>
    <%= f.input :side_box_1_text %>
    <%= f.input :side_box_2_title %>
    <%= f.input :side_box_2_text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<div class="span10 offset1">
	<h1>Editing <%= best_in_place @site, :domain, nil: 'Enter classified URL.' %> <%= link_to 'Exit Editor', @site, class: 'btn' %></h1>
	<%= best_in_place @site, :meta_title, nil: 'Meta Title' %><br>
	<%= best_in_place @site, :meta_keywords, nil: 'Meta Keywords' %><br>
	<%= best_in_place @site, :meta_description, nil: 'Meta Description' %>
</div>
<div class="span10 offset1">
	<div class="well" style="text-align:center;">
		<h2><%= best_in_place @site, :hero_unit, nil: 'Enter a Headline To Grab Attention.' %></h2>
	</div>
</div>

<div class="span7 offset1">	
	<%= render 'classifieds/display-table' %>

</div>
<div class="span3">
	<%= link_to 'Edit Site', edit_site_path(@site), class: 'btn btn-block' %>
	<div class="well well-small">
		<h3><%= best_in_place @site, :call_to_subscribe, type: :textarea, nil: 'Make call to enter email.' %></h3>
			<%= render 'subscribers/form' %>
	</div>
	<div class="well well-small">
		<h4><%= best_in_place @site, :side_box_1_title, nil: 'Side Box1 Title' %></h4>
		<span class="lead"><%= best_in_place @site, :side_box_1_text, type: :textarea, nil: 'Enter Side Box Text' %></span>
	</div>
	<div class="well well-small">
		<%= link_to 'Browse Packages', '/packages', class: 'btn btn-danger btn-block btn-large' %>
	</div>
	<div class="well">
		<h5><%= best_in_place @site, :side_box_2_title, nil: 'Side Box2 Title' %></h5>
		<%= best_in_place @site, :side_box_2_text, type: :textarea, sanitize: false, nil: 'Sidebox Unsanitized for use with html' %>
	</div>	
</div>

app/views/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sites.each do |site| %>
  <tr>
    <td><%= site.name %></td>
    <td><%= link_to 'Show', site %></td>
    <td><%= link_to 'Edit', edit_site_path(site) %></td>
    <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<%= cache "site-#{@site.id}" do %>
<div class="span10 offset1">
	<div class="well" style="text-align:center;">
		<h1><%= @site.hero_unit %></h1>
	</div>
</div>

<div class="span7 offset1">
	<%= render 'display-table' %>
</div>
<div class="span3">
	<div class="owner">
		<%= link_to 'Edit Site', edit_site_path(@site), class: 'btn btn-block' %>
	</div>
	<div class="well well-small">
		<h3><%= @site.call_to_subscribe %></h3>
			<%= render 'subscribers/form' %>
	</div>
	<div class="well well-small">
		<h4><%= @site.side_box_1_title %></h4>
		<span class="lead"><%= @site.side_box_1_text %></span>
	</div>
	<div class="well well-small">
		<%= link_to 'Browse Packages', '/packages', class: 'btn btn-danger btn-block btn-large' %>
	</div>
	<div class="well">
		<h5><%= @site.side_box_2_title %></h5>
		<%= raw @site.side_box_2_text %>
	</div>	
</div>
<% end %>

app/views/sites/show.js.erb
$('#web_results').append('<%= j render(@web_results) %>');
<% if @web_results.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@web_results) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/sites/sitemap.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
	<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
		<url>
			<loc>http://www.Rent-Tallahassee.com</loc>
			<changefreq>always</changefreq>
			<priority>1.0</priority>
		</url>
		<url>
			<loc>http://www.Rent-Philadelphia.com</loc>
			<changefreq>always</changefreq>
			<priority>1.0</priority>
		</url>
		<url>
			<loc>http://www.Rent-San-Francisco.com</loc>
			<changefreq>always</changefreq>
			<priority>1.0</priority>
		</url>
		<url>
			<loc>http://www.Rentals-in-FL.com</loc>
			<changefreq>always</changefreq>
			<priority>1.0</priority>
		</url>
		<% @feed_entries.each do |web| %>
			<url>
				<% if web.site_id == 1 %>
					<loc>http://www.Rent-Tallahassee.com/feed_entries/<%= web.id %>-<%= web.name.parameterize %></loc>
				<% end %>
				<% if web.site_id == 2 %>
					<loc>http://www.findfrackingjobs.com/feed_entries/<%= web.id %>-<%= web.name.parameterize %></loc>
				<% end %>
				<% if web.site_id == 3 %>
					<loc>http://www.Rent-Philadelphia.com/feed_entries/<%= web.id %>-<%= web.name.parameterize %></loc>
				<% end %>
				<% if web.site_id == 4 %>
					<loc>http://www.Rent-San-Francisco.com/feed_entries/<%= web.id %>-<%= web.name.parameterize %></loc>
				<% end %>
				<% if web.site_id == 5 %>
					<loc>http://www.Rentals-in-FL.com/feed_entries/<%= web.id %>-<%= web.name.parameterize %></loc>
				<% end %>
				<changefreq>always</changefreq>
				<priority>0.9</priority>
			</url>
		<% end %>
		<url>
			<loc>http://www.Rent-Tallahassee.com/packages</loc>
			<changefreq>always</changefreq>
			<priority>0.5</priority>
		</url>
	</urlset>